trigger:
  branches:
    include:
      - feature/cicd-sync-iothub  # all branches
  paths:
    exclude:
      - '**/*.md'
      - 'docs/*'
      - '.gitignore'
      - '.gitattributes'
      - '.gitmodules'
      - '.editorconfig'
      - 'LICENSE*'
      - 'THIRD-PARTY-NOTICES.md'

pr:
  branches:
    include:
      - main
      - master
  paths:
    exclude:
      - '**/*.md'
      - 'docs/*'
      - '.gitignore'
      - '.gitattributes'
      - '.gitmodules'
      - '.editorconfig'
      - 'LICENSE*'
      - 'THIRD-PARTY-NOTICES.md'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: TARGET_BRANCH
    value: feature/cicd-sync-iothub
  - name: CAKE_VERSION
    value: 1.1.0
  - name: BUILD_CONFIGURATION
    value: Release

stages:
  - stage: BuildAndTest
    displayName: "Build and Test"
    condition: always()
    jobs: 
      - template: templates/build-test.yml
    

  - stage: VersionBump
    displayName: "Version Bump"
    dependsOn: BuildAndTest
    condition: and(eq(variables['Build.SourceBranch'], format('refs/heads/{0}', variables['TARGET_BRANCH'])), eq(variables['Build.Reason'], 'IndividualCI'))
    jobs:
      - template: templates/version-bump.yml

  - stage: Container
    displayName: "Build and Push Container"
    dependsOn: VersionBump
    condition: and(eq(variables['Build.SourceBranch'], format('refs/heads/{0}', variables['TARGET_BRANCH'])), eq(variables['Build.Reason'], 'IndividualCI'))
    variables:
      VERSION: $[ stageDependencies.VersionBump.version_bump.outputs['SetVersion.version'] ]
    jobs:
      - template: templates/build-push-container.yml
  
  - stage: iot_hub_deployment 
    displayName: "IoT Hub Deployment"
    dependsOn: [Container, VersionBump]
    condition: and(succeeded('VersionBump'), succeeded('Container'))
    variables:
      VERSION: $[ stageDependencies.VersionBump.version_bump.outputs['SetVersion.version'] ]
    jobs: 
      - template: templates/iot-hub-deployment.yml

  - stage: SyncRepo
    displayName: "Sync to GitHub"
    dependsOn: iot_hub_deployment
    condition: always()
    jobs: 
      - template: templates/repo-sync.yml


