jobs: 
    - job: build_and_push_container
      variables: 
        - group: DockerLogin

      steps:
        - checkout: self
          submodules: true
          persistCredentials: true

        - script: |
            git fetch origin $(TARGET_BRANCH)
            git reset --hard origin/$(TARGET_BRANCH)
            echo "Updated to latest commit with version bump"
          displayName: 'Update to latest commit'

        - task: Cache@2
          inputs:
            key: 'nuget | "$(Agent.OS)" | **/*.csproj, **/Directory.Packages.props'
            restoreKeys: |
              nuget | "$(Agent.OS)"
            path: ~/.nuget/packages

        - task: Cache@2
          inputs:
            key: 'cake-tools | "$(Agent.OS)" | build.cake'
            restoreKeys: |
              cake-tools | "$(Agent.OS)"
            path: ~/tools
            
        - script: chmod +x build.sh
          displayName: "Make build.sh executable"

        - script: ./build.sh --target=Build --configuration="$BUILD_CONFIGURATION"
          displayName: "Build .NET"

        - script: |
            echo $(PUSH_PASS) | docker login $(LOGIN_SERVER) -u $(PUSH_USER) --password-stdin
          displayName: "Login to Azure Container Registry"

        - script: |
            VERSION=$(VERSION)
            ./build.sh --target=PublishContainer --configuration="$BUILD_CONFIGURATION" --property="ContainerRepository=$(IMAGE_NAME)"
            docker tag $(IMAGE_NAME):$VERSION $(LOGIN_SERVER)/$(IMAGE_NAME):$VERSION-x64
            docker push $(LOGIN_SERVER)/$(IMAGE_NAME):$VERSION-x64

            ./build.sh --target=PublishContainer --configuration="$BUILD_CONFIGURATION" --property="ContainerRepository=$(IMAGE_NAME)" --container-arch=arm64
            docker tag $(IMAGE_NAME):$VERSION $(LOGIN_SERVER)/$(IMAGE_NAME):$VERSION-arm64
            docker push $(LOGIN_SERVER)/$(IMAGE_NAME):$VERSION-arm64

            docker manifest annotate $(LOGIN_SERVER)/$(IMAGE_NAME):$VERSION \
              $(LOGIN_SERVER)/$(IMAGE_NAME):$VERSION-x64 --arch amd64 --os linux
            
            docker manifest annotate $(LOGIN_SERVER)/$(IMAGE_NAME):$VERSION \
              $(LOGIN_SERVER)/$(IMAGE_NAME):$VERSION-arm64 --arch arm64 --os linux

            docker manifest push $(LOGIN_SERVER)/$(IMAGE_NAME):$VERSION

          displayName: "Build and Publish Container"
