jobs: 
    - job: Sync_repo_GitHub
      variables: 
        - group: Credentials
      steps:
        - checkout: self
          fetchDepth: 0   # Fetch full history for all branches

        - script: |
            git config --global user.name "Hai Chu"
            git config --global user.email "hai.m.chu20@gmail.com"
        
            GITHUB_URL="https://$(GITHUB_TOKEN)@github.com/$(GITHUB_REPO).git"
            git remote add github $GITHUB_URL

            # Fetch all branches and tags from Azure DevOps
            git fetch origin "+refs/heads/*:refs/remotes/origin/*" --prune
            git fetch origin "+refs/tags/*:refs/tags/*" --prune

            # Fetch all branches from GitHub
            git fetch github "+refs/heads/*:refs/remotes/github/*" --prune

            # Push each branch except origin/HEAD
            for branch in $(git for-each-ref --format='%(refname:short)' refs/remotes/origin/ | grep -v '^origin/HEAD$'); do
            branch_name=${branch#origin/}
            echo "Syncing branch $branch_name to GitHub"
            
            # Check if there are differences between Azure DevOps and GitHub
            if git show-ref --verify --quiet refs/remotes/github/$branch_name; then
              # Branch exists on GitHub, compare them
              if git diff --quiet $branch_name github/$branch_name 2>/dev/null; then
                echo "Branch is already in sync"
                continue
              else
                echo "Changes detected syncing"
              fi
            else
              echo "New branch syncing"
            fi

            # Push directly and skip CI using push options
            git push github "refs/remotes/origin/$branch_name:refs/heads/$branch_name" --force --no-verify -o ci.skip
            done

            # Push tags too
            git push github --tags --force --no-verify

            # Delete GitHub branches that no longer exist in Azure DevOps
            for gh_branch in $(git for-each-ref --format='%(refname:short)' refs/remotes/github/ | grep -v '^github/HEAD$'); do
            branch_name=${gh_branch#github/}
            if ! git show-ref --verify --quiet refs/remotes/origin/$branch_name; then
                echo "Deleting GitHub branch $branch_name (deleted in Azure DevOps)"
                git push github --delete $branch_name || true
            fi
            done
          displayName: "Sync Azure DevOps → GitHub (with deletions and skip CI)"
